version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "📦 Installing zip and dependencies..."
      - pip install --upgrade pip
      - yum update -y && yum install -y zip

  build:
    commands:
      - echo "📦 Packaging Lambda functions..."
      - zip -j RegisterUser.zip lambda/RegisterUser/lambda_function.py
      - zip -j GetUserPreferences.zip lambda/GetUserPreferences/lambda_function.py
      - zip -j LoginUser.zip lambda/LoginUser/lambda_function.py
      - zip -j UpdateUserPreferences.zip lambda/UpdateUserPreferences/lambda_function.py
      - zip -j GetWeatherByLocation.zip lambda/GetWeatherByLocation/lambda_function.py

      - echo "🌐 Uploading frontend to S3..."
      - aws s3 sync frontend/ s3://windy-app2/ --delete || echo "S3 sync failed — check bucket or IAM permissions"

  post_build:
    commands:
      - echo "🚀 Updating Lambda functions (must already exist)..."
      - aws lambda update-function-code --function-name RegisterUser --zip-file fileb://RegisterUser.zip
      - aws lambda update-function-code --function-name GetUserPreferences --zip-file fileb://GetUserPreferences.zip
      - aws lambda update-function-code --function-name LoginUser --zip-file fileb://LoginUser.zip
      - aws lambda update-function-code --function-name UpdateUserPreferences --zip-file fileb://UpdateUserPreferences.zip
      - aws lambda update-function-code --function-name GetWeatherByLocation --zip-file fileb://GetWeatherByLocation.zip

artifacts:
  files:
    - '*.zip'
