version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "🔧 Installing dependencies..."
      - pip install --upgrade pip
      - yum update -y && yum install -y zip

  build:
    commands:
      - echo "📦 Zipping Lambda functions..."
      - zip -j RegisterUser.zip lambda_functions/RegisterUser/lambda_function.py
      - zip -j GetUserPreferences.zip lambda_functions/GetUserPreferences/lambda_function.py
      - zip -j LoginUser.zip lambda_functions/LoginUser/lambda_function.py
      - zip -j UpdateUserPreferences.zip lambda_functions/UpdateUserPreferences/lambda_function.py
      - zip -j GetWeatherByLocation.zip lambda_functions/GetWeatherByLocation/lambda_function.py

      - echo "🌍 Uploading frontend to S3..."
      - aws s3 sync frontend/ s3://weather-frontend-app/ --delete

  post_build:
    commands:
      - echo "🚀 Updating Lambda functions..."
      - aws lambda update-function-code --function-name RegisterUser --zip-file fileb://RegisterUser.zip
      - aws lambda update-function-code --function-name GetUserPreferences --zip-file fileb://GetUserPreferences.zip
      - aws lambda update-function-code --function-name LoginUser --zip-file fileb://LoginUser.zip
      - aws lambda update-function-code --function-name UpdateUserPreferences --zip-file fileb://UpdateUserPreferences.zip
      - aws lambda update-function-code --function-name GetWeatherByLocation --zip-file fileb://GetWeatherByLocation.zip

artifacts:
  files:
    - '*.zip'
