version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "📦 Installing zip and setting region..."
      - pip install --upgrade pip
      - zip --version || (command -v yum && yum install -y zip) || echo "zip already installed or yum not available"
      - export AWS_DEFAULT_REGION=eu-north-1

  build:
    commands:
      - echo "🔍 Listing available Lambda function source files..."
      - find lambda_functions/

      - echo "📦 Packaging Lambda function code into zip files..."
      - zip -j register_user.zip lambda_functions/RegisterUser/register_user.py
      - zip -j get_user_prefs.zip lambda_functions/GetUserPreferences/get_user_prefs.py
      - zip -j login_user.zip lambda_functions/LoginUser/login_user.py
      - zip -j update_user_prefs.zip lambda_functions/UpdateUserPreferences/update_user_prefs.py
      - zip -j get_weather.zip lambda_functions/GetWeatherByLocation/get_weather.py

      - echo "🌐 Syncing frontend to S3..."
      - ls -al frontend/ || echo "frontend/ directory not found or empty"
      - aws s3 sync frontend/ s3://windy-app2/ --delete || echo "S3 sync failed — check IAM permissions or bucket name"

  post_build:
    commands:
      - echo "🧪 Validating Lambda zip files..."
      - unzip -l register_user.zip
      - unzip -l get_user_prefs.zip
      - unzip -l login_user.zip
      - unzip -l update_user_prefs.zip
      - unzip -l get_weather.zip

      - echo "🚀 Deploying Lambda functions in eu-north-1..."

      - |
        for fn in register_user get_user_prefs login_user update_user_prefs get_weather; do
          zip_file="${fn}.zip"
          handler="${fn}.lambda_handler"
          echo "→ Checking if $fn exists..."

          if aws lambda get-function --function-name "$fn" >/dev/null 2>&1; then
            echo "✅ Updating existing function: $fn"
            aws lambda update-function-code \
              --function-name "$fn" \
              --zip-file "fileb://${zip_file}"
          else
            echo "🆕 Creating new function: $fn"
            aws lambda create-function \
              --function-name "$fn" \
              --runtime python3.11 \
              --role arn:aws:iam::651706765226:role/your-lambda-execution-role \
              --handler "$handler" \
              --zip-file "fileb://${zip_file}" \
              --region eu-north-1
          fi
        done

artifacts:
  files:
    - '*.zip'
