version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "📦 Installing dependencies..."
      - pip install --upgrade pip
      - which zip || (command -v yum && yum install -y zip) || (command -v apt-get && apt-get update && apt-get install -y zip) || echo "zip already installed or no package manager available"

  build:
    commands:
      - echo "📦 Packaging Lambda functions..."
      - zip -j RegisterUser.zip lambda_functions/RegisterUser/register_user.py
      - zip -j GetUserPreferences.zip lambda_functions/GetUserPreferences/get_user_prefs.py
      - zip -j LoginUser.zip lambda_functions/LoginUser/login_user.py
      - zip -j UpdateUserPreferences.zip lambda_functions/UpdateUserPreferences/update_user_prefs.py
      - zip -j GetWeatherByLocation.zip lambda_functions/GetWeatherByLocation/get_weather.py

      - echo "🌐 Uploading frontend to S3..."
      - ls -al frontend/ || echo "frontend/ directory not found or empty"
      - aws s3 sync frontend/ s3://weather-frontend-app/ --delete || echo "S3 sync failed — check bucket name or IAM permissions"

  post_build:
    commands:
      - echo "🧪 Validating zip files..."
      - unzip -l RegisterUser.zip || echo "❌ RegisterUser.zip is missing or invalid"
      - unzip -l GetUserPreferences.zip || echo "❌ GetUserPreferences.zip is missing or invalid"
      - unzip -l LoginUser.zip || echo "❌ LoginUser.zip is missing or invalid"
      - unzip -l UpdateUserPreferences.zip || echo "❌ UpdateUserPreferences.zip is missing or invalid"
      - unzip -l GetWeatherByLocation.zip || echo "❌ GetWeatherByLocation.zip is missing or invalid"

      - echo "🚀 Updating Lambda functions (must already exist)..."
      - aws lambda update-function-code --function-name RegisterUser --zip-file fileb://RegisterUser.zip
      - aws lambda update-function-code --function-name GetUserPreferences --zip-file fileb://GetUserPreferences.zip
      - aws lambda update-function-code --function-name LoginUser --zip-file fileb://LoginUser.zip
      - aws lambda update-function-code --function-name UpdateUserPreferences --zip-file fileb://UpdateUserPreferences.zip
      - aws lambda update-function-code --function-name GetWeatherByLocation --zip-file fileb://GetWeatherByLocation.zip

artifacts:
  files:
    - '*.zip'
