version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - zip --version || (command -v yum && yum install -y zip) || echo "zip already installed or yum not available"
      - export AWS_DEFAULT_REGION=eu-north-1

  build:
    commands:
      - echo "Listing all Lambda source files:"
      - find lambda_functions/

      - echo "Packaging Lambda functions..."
      - zip -j register_user.zip lambda_functions/RegisterUser/register_user.py
      - zip -j get_user_prefs.zip lambda_functions/GetUserPreferences/get_user_prefs.py
      - zip -j login_user.zip lambda_functions/LoginUser/login_user.py
      - zip -j update_user_prefs.zip lambda_functions/UpdateUserPreferences/update_user_prefs.py
      - zip -j get_weather.zip lambda_functions/GetWeatherByLocation/get_weather.py

      - echo "Checking frontend directory..."
      - ls -al frontend/ || echo "frontend/ directory not found or empty"

      - echo "Uploading static frontend to S3..."
      - aws s3 sync frontend/ s3://windy-app2/ --delete || echo "S3 sync failed — check IAM permissions and bucket name"

  post_build:
    commands:
      - echo "Verifying Lambda zip files..."
      - unzip -l register_user.zip || echo "register_user.zip missing or invalid"
      - unzip -l get_user_prefs.zip || echo "get_user_prefs.zip missing or invalid"
      - unzip -l login_user.zip || echo "login_user.zip missing or invalid"
      - unzip -l update_user_prefs.zip || echo "update_user_prefs.zip missing or invalid"
      - unzip -l get_weather.zip || echo "get_weather.zip missing or invalid"

      - echo "Updating Lambda functions in eu-north-1..."
      - aws lambda update-function-code --function-name register_user --zip-file fileb://register_user.zip
      - aws lambda update-function-code --function-name get_user_prefs --zip-file fileb://get_user_prefs.zip
      - aws lambda update-function-code --function-name login_user --zip-file fileb://login_user.zip
      - aws lambda update-function-code --function-name update_user_prefs --zip-file fileb://update_user_prefs.zip
      - aws lambda update-function-code --function-name get_weather --zip-file fileb://get_weather.zip

artifacts:
  files:
    - '*.zip'
